# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "test"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
    template_toolkit:
        ENCODING: utf8


plugins:
  DBIC:
    default:
      dsn: dbi:mysql:dancetest
      schema_class: Strehler::StrehlerDB
      user: dancetest
      pass: dancetest
      options:
        RaiseError: 1
        PrintError: 1
        mysql_enable_utf8: 1

admin_secured: true
languages: ['it', 'en'] 
